<?php

namespace Generators\Commands;

use Illuminate\Console\GeneratorCommand;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class CreateContractCommand extends GeneratorCommand
{
    protected $signature = 'generators:create-command
        {name : awdawdawdwa}
        {--force : recreate class}
    ';

    /**
     * @inheritDoc
     */
    protected function getStub()
    {
        return __DIR__ . '/../stubs/create-command.stub';
    }

    protected function buildClass($name)
    {
        dd(Schema::getColumnListing('users'));
        return parent::buildClass($name); // TODO: Change the autogenerated stub
    }
}